# CircleCI configuration file

version: 2.1
executors:
  go:
    docker:
      - image: cimg/go:1.20.4

parameters:
  goreleaser_binary:
    description: The path of the goreleaser binary
    type: string
    default: "/tmp/goreleaser"

jobs:
  lint-test:
    executor: go
    steps:
      - checkout
      - run: make lint
      - run: make test
  build:
    executor: go
    parameters:
      gorelaser_url:
        description: Goreleaser 1.18.2 download URL
        type: string
        default: https://github.com/goreleaser/goreleaser/releases/download/v1.18.2/goreleaser_Linux_x86_64.tar.gz
      gorelaser_output_name:
        description: Goreleaser 1.18.2 downloaded file name
        type: string
        default: << pipeline.parameters.goreleaser_binary >>.tar.gz
    steps:
      - checkout
      - run:
          name: Download Goreleaser
          command: curl -fLo << parameters.gorelaser_output_name >> << parameters.gorelaser_url >>
      - run:
          name: Unarchive
          command: tar -xf << parameters.gorelaser_output_name >> << pipeline.parameters.goreleaser_binary >>
      - run:
          name: Build
          command: << pipeline.parameters.goreleaser_binary >> build
      - save_cache:
          key: binaries
          paths:
            - dist
            - << pipeline.parameters.goreleaser_binary >>
  publish:
    executor: go
    steps:
      - restore_cache:
          keys:
            - binaries
      - run:
          name: release
          command: << pipeline.parameters.goreleaser_binary >> release


workflows:
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v([0-9]+\.){2}[0-9]+/
      - publish:
          requires:
            - build
  check:
    jobs:
      - lint-test
