# CircleCI configuration file

version: 2.1
executors:
  go:
    docker:
      - image: cimg/go:1.20.4

jobs:
  lint-test:
    executor: go
    steps:
      - checkout
      - run: make lint
      - run: make test
  generate-docs:
    executor: go
    steps:
      - checkout
      - run: make generate-doc


workflows:
  publish_to_registry:
    jobs:
      - lint-test
      - generate-docs
