name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - babybabycloud
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did actually happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: What is the expectation?
      placeholder: Please tellus what is you expectation
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.0 (Default)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What is operation system that this bug is found
      options:
        - freebsd
        - windows
        - linux
        - darwin
  - type: dropdown
    id: arch
    attributes:
      label: Arch
      description: What is the arch that this bug is found
      options:
        - amd64
        - '386'
        - arm
        - arm64
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please provide more details
      placeholder: Please provide more details
    valications:
      required: true
